# Generated by Django 2.2.7 on 2019-11-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='admin',
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
