# Generated by Django 2.2.7 on 2019-11-25 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='user_id',
            new_name='user',
        ),
    ]
