# Generated by Django 2.2.7 on 2019-12-02 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftlist', '0003_groupmember_usergroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmember',
            old_name='memeber',
            new_name='member',
        ),
    ]
